version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"

  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "daily"
    automerged_updates:
      - match:
          update_type: "in_range"
