name: vet

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  vet:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: ^1.18
          check-latest: true
          cache: true

      - name: Vet
        run: go vet ./...

      - name: Test
        run: go test ./...
